aliases: []
creation_timestamp: 1705604850985
current_stage: None
description: null
last_updated_timestamp: 1705604850985
name: naive_model
run_id: 15fd9040f103430a8c72affa9e58cdd0
run_link: null
source: /home/angry/mlops_4/mlflow/1/15fd9040f103430a8c72affa9e58cdd0/artifacts/naive_model
status: READY
status_message: null
storage_location: /home/angry/mlops_4/mlflow/1/15fd9040f103430a8c72affa9e58cdd0/artifacts/naive_model
user_id: null
version: 6
