aliases: []
creation_timestamp: 1705605361890
current_stage: None
description: null
last_updated_timestamp: 1705605361890
name: theta_model
run_id: 67038e1593284e1abf34c0368094699b
run_link: null
source: /home/angry/mlops_4/mlflow/3/67038e1593284e1abf34c0368094699b/artifacts/theta_model
status: READY
status_message: null
storage_location: /home/angry/mlops_4/mlflow/3/67038e1593284e1abf34c0368094699b/artifacts/theta_model
user_id: null
version: 8
