aliases: []
creation_timestamp: 1705604324606
current_stage: None
description: null
last_updated_timestamp: 1705604324606
name: exp_model
run_id: 8da6d9572bb34ea7aa9ce526d911df23
run_link: null
source: /home/angry/mlops_4/mlflow/2/8da6d9572bb34ea7aa9ce526d911df23/artifacts/exp_model
status: READY
status_message: null
storage_location: /home/angry/mlops_4/mlflow/2/8da6d9572bb34ea7aa9ce526d911df23/artifacts/exp_model
user_id: null
version: 3
