aliases: []
creation_timestamp: 1705604278950
current_stage: None
description: null
last_updated_timestamp: 1705604278950
name: naive_model
run_id: 4c3096d9fd4f4345991a98558ca05dfd
run_link: null
source: /home/angry/mlops_4/mlflow/1/4c3096d9fd4f4345991a98558ca05dfd/artifacts/naive_model
status: READY
status_message: null
storage_location: /home/angry/mlops_4/mlflow/1/4c3096d9fd4f4345991a98558ca05dfd/artifacts/naive_model
user_id: null
version: 3
