aliases: []
creation_timestamp: 1705605426138
current_stage: None
description: null
last_updated_timestamp: 1705605426138
name: naive_model
run_id: 868a3a617d014b49b04a5c4fd5c2245f
run_link: null
source: /home/angry/mlops_4/mlflow/1/868a3a617d014b49b04a5c4fd5c2245f/artifacts/naive_model
status: READY
status_message: null
storage_location: /home/angry/mlops_4/mlflow/1/868a3a617d014b49b04a5c4fd5c2245f/artifacts/naive_model
user_id: null
version: 9
