aliases: []
creation_timestamp: 1705605031207
current_stage: None
description: null
last_updated_timestamp: 1705605031207
name: naive_model
run_id: 9c8c946655264bfdab782d77e28b29a4
run_link: null
source: /home/angry/mlops_4/mlflow/1/9c8c946655264bfdab782d77e28b29a4/artifacts/naive_model
status: READY
status_message: null
storage_location: /home/angry/mlops_4/mlflow/1/9c8c946655264bfdab782d77e28b29a4/artifacts/naive_model
user_id: null
version: 7
