aliases: []
creation_timestamp: 1705605082787
current_stage: None
description: null
last_updated_timestamp: 1705605082787
name: exp_model
run_id: 415cf3ea13804473afc55997c000fe6a
run_link: null
source: /home/angry/mlops_4/mlflow/2/415cf3ea13804473afc55997c000fe6a/artifacts/exp_model
status: READY
status_message: null
storage_location: /home/angry/mlops_4/mlflow/2/415cf3ea13804473afc55997c000fe6a/artifacts/exp_model
user_id: null
version: 7
