aliases: []
creation_timestamp: 1705604897269
current_stage: None
description: null
last_updated_timestamp: 1705604897269
name: exp_model
run_id: f717e7f4af104647b53cd91d3d54721e
run_link: null
source: /home/angry/mlops_4/mlflow/2/f717e7f4af104647b53cd91d3d54721e/artifacts/exp_model
status: READY
status_message: null
storage_location: /home/angry/mlops_4/mlflow/2/f717e7f4af104647b53cd91d3d54721e/artifacts/exp_model
user_id: null
version: 6
