aliases: []
creation_timestamp: 1705604392431
current_stage: None
description: null
last_updated_timestamp: 1705604392431
name: theta_model
run_id: f82ceef2f0a24d10bbae508d4198e521
run_link: null
source: /home/angry/mlops_4/mlflow/3/f82ceef2f0a24d10bbae508d4198e521/artifacts/theta_model
status: READY
status_message: null
storage_location: /home/angry/mlops_4/mlflow/3/f82ceef2f0a24d10bbae508d4198e521/artifacts/theta_model
user_id: null
version: 3
